# Generated by Django 4.1.6 on 2023-04-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("animalType", models.CharField(max_length=200)),
                ("breed", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="animals/images/")),
            ],
        ),
    ]
